# **Section 1 : Libraries**

### Question 1

A library in programming is a collection of code already written by someone else that you or a programmer can use to help perform tasks without having to write everything yourself or from the scratch to make work easier and faster and to save time, which you can simply import and use the functions needed instead of building them yourself.

**For example**, if you want your program to do calculations or work with data, you can use a library that already has those features built in. This makes coding easier, faster, and helps you avoid mistakes.

### Question 2

**NumPy**— NumPy is one of the python library used for working with numbers, arrays, and for fast mathematical calculations.

**Pandas** — Pandas is a Python library used for organizing, analyzing, and working with data in tables like the spreadsheets.

# **Section 2 : NumPy**

### Question 3

Creating a NumPy array from a list of 6 elements

In [ ]:
import numpy as np

In [ ]:
my_array = np.array([3, 6, 9, 12, 15, 18, 21])

In [ ]:
print(my_array)

[ 3  6  9 12 15 18 21]

# **Section 3: Pandas - Building and Exploring a Dataset**

### **Step 1 : Creating Student Dataset**

In [ ]:
import pandas as pd

In [ ]:
student_data = {
    "StudentID":    ["S010","S011","S012","S013","S014","S015","S016","S017"],
    "Name":         ["Wanita Bukie","John Selman","David Joe","Michael James","Vera Judge", "Jeffrey cole" ,"Brian Moon",
                     "Wisdom Karen" ],
    "Age":          [20, 22, 21, 23, 22, 24, 23, 24,],
    "Department":   ["Medicine","Dentistry","Radiography", "Pharmacy","Medical Lab","Law", "Nursing", "Accountancy"],
    "Score":        [ 70, 55, 78, 58, 62, 91, 64, 85,],
    "Grade":        ["A","C","A","C","B","A","B","A"]
}

In [ ]:
df = pd.DataFrame(student_data)

In [ ]:
df

  StudentID           Name  Age   Department  Score Grade
0      S010   Wanita Bukie   20     Medicine     70     A
1      S011    John Selman   22    Dentistry     55     C
2      S012      David Joe   21  Radiography     78     A
3      S013  Michael James   23     Pharmacy     58     C
4      S014     Vera Judge   22  Medical Lab     62     B
5      S015   Jeffrey cole   24          Law     91     A
6      S016     Brian Moon   23      Nursing     64     B
7      S017   Wisdom Karen   24  Accountancy     85     A

### **Step 2 : Checking the first (5) rows and the last (3)rows.**

In [ ]:
df.head(5)

  StudentID           Name  Age   Department  Score Grade
0      S010   Wanita Bukie   20     Medicine     70     A
1      S011    John Selman   22    Dentistry     55     C
2      S012      David Joe   21  Radiography     78     A
3      S013  Michael James   23     Pharmacy     58     C
4      S014     Vera Judge   22  Medical Lab     62     B

In [ ]:
df.tail(3)

  StudentID          Name  Age   Department  Score Grade
5      S015  Jeffrey cole   24          Law     91     A
6      S016    Brian Moon   23      Nursing     64     B
7      S017  Wisdom Karen   24  Accountancy     85     A

### **Step 3: Checking the shape of the data frame**

In [ ]:
df.shape # (rows, columns)

(8, 6)

**Text Cell explaning the output Of Step 3**

The result from df.shape shows the number of rows and columns in the DataFrame.

The first number represents the number of rows (students) in the dataset,

The second number represents the number of columns ie; StudentID, Name, Age, Department, Score, and Grade.

That is the output is (8, 6), it means the dataset contains 8 students and 6 columns.

### **Step 4: DataFrame Information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   8 non-null      object
 1   Name        8 non-null      object
 2   Age         8 non-null      int64
 3   Department  8 non-null      object
 4   Score       8 non-null      int64
 5   Grade       8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

**Text Cell explaning the output Of Step 4**

The df.info() method gives is a summary of the DataFrame including column names, data types, and number of non-null values.

Based on the dataset, all columns display 8 non-null values, which means there are no missing values in the dataset.

### **Step 5: Finding the unique and n.unique Values**

In [ ]:
department_series = df['Department']
name_series = df['name']

KeyError: 'name'

In [ ]:
department_series.unique()

In [ ]:
department_series.nunique()

### **Step 6: Reflect**

Exploring my dataset, I found it interesting that each departments had not more than one students,each student performed well, with many receiving grades A and B. It was surprising to see how diverse the dataset became just from creating a small group of students.